# Generated by Django 2.2.4 on 2020-09-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQuote', '0002_quotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='message',
            field=models.TextField(max_length=255),
        ),
    ]
